# Generated by Django 3.0 on 2020-01-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Subject', models.CharField(max_length=40)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
