# Generated by Django 3.0 on 2020-02-11 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Subject',
            new_name='Bike',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Comment',
        ),
        migrations.AddField(
            model_name='reservation',
            name='datefrom',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='dateto',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
